export const LOAD_JSON_DATA = 'LOAD_JSON_DATA';

export const TOGGLE_PAGE_READY = 'TOGGLE_PAGE_READY';

export const TOGGLE_SCROLLTOP_ANIMATION = 'TOGGLE_SCROLLTOP_ANIMATION';
// export const CHANGE_PROJECT_ROUTE = 'CHANGE_PROJECT_ROUTE';
