// common
export const TOGGLE_HEADER_ANIMATION = 'TOGGLE_HEADER_ANIMATION';

// navbar
export const UPDATE_NAVBAR_SCROLLSPY = 'UPDATE_NAVBAR_SCROLLSPY';
export const SCROLL_NAVBAR_SECTION = 'SCROLL_NAVBAR_SECTION';
export const TOGGLE_NAVBAR_COLLAPSE = 'TOGGLE_NAVBAR_COLLAPSE';

// footer
export const TOGGLE_FOOTER_ANIMATION = 'TOGGLE_FOOTER_ANIMATION';
