// home
export const LOAD_JSON_DATA = 'LOAD_JSON_DATA';
export const TOGGLE_HOME_READY = 'TOGGLE_HOME_READY';
export const TOGGLE_HOME_INTRO_ANIMATION = 'TOGGLE_HOME_INTRO_ANIMATION';
export const CYCLE_HOME_TEXT_COLOR = 'CYCLE_HOME_TEXT_COLOR';

// about
export const TOGGLE_ABOUT_ICON_ANIMATION = 'TOGGLE_ABOUT_ICON_ANIMATION';

// affiliation
export const UPDATE_AFFILIATION_SCROLLSPY = 'UPDATE_AFFILIATION_SCROLLSPY';

// portfolio
export const CHANGE_PORTFOLIO_FILTER = 'CHANGE_PORTFOLIO_FILTER';
export const TOGGLE_PORTFOLIO_FILTER_ANIMATION = 'TOGGLE_PORTFOLIO_FILTER_ANIMATION';
export const TOGGLE_PORTFOLIO_THUMBNAIL_ANIMATION = 'TOGGLE_PORTFOLIO_THUMBNAIL_ANIMATION';
export const TOGGLE_PORTFOLIO_BRAND_ANIMATION = 'TOGGLE_PORTFOLIO_BRAND_ANIMATION';

// skills
export const TOGGLE_SKILLS_PROGRESSBAR_ANIMATION = 'TOGGLE_SKILLS_PROGRESSBAR_ANIMATION';

// stats
export const TOGGLE_STATS_COUNTER_ANIMATION = 'TOGGLE_STATS_COUNTER_ANIMATION';
export const TOGGLE_STATS_GITHUB_ANIMATION = 'TOGGLE_STATS_GITHUB_ANIMATION';

// pubs
export const TOGGLE_PUBS_ENTRY_ANIMATION = 'TOGGLE_PUBS_ENTRY_ANIMATION';

// contact
export const CHANGE_CONTACT_FIELD = 'CHANGE_CONTACT_FIELD';
export const SUBMIT_CONTACT_EMAIL_WAIT = 'SUBMIT_CONTACT_EMAIL_WAIT';
export const SUBMIT_CONTACT_EMAIL_SUCCESS = 'SUBMIT_CONTACT_EMAIL_SUCCESS';
export const SUBMIT_CONTACT_EMAIL_ERROR = 'SUBMIT_CONTACT_EMAIL_ERROR';
export const SUBMIT_CONTACT_EMAIL_RESET = 'SUBMIT_CONTACT_EMAIL_RESET';
export const TOGGLE_AUDIO_PLAYBACK = 'TOGGLE_AUDIO_PLAYBACK';
export const TOGGLE_CONTACT_ICON_ANIMATION = 'TOGGLE_CONTACT_ICON_ANIMATION';
export const TOGGLE_CONTACT_ITEM_ANIMATION = 'TOGGLE_CONTACT_ITEM_ANIMATION';
