// common
export const TOGGLE_HEADER_ANIMATION = 'TOGGLE_HEADER_ANIMATION';

// home
export const LOAD_JSON_DATA = 'LOAD_JSON_DATA';

// about
export const TOGGLE_ABOUT_ICON_ANIMATION = 'TOGGLE_ABOUT_ICON_ANIMATION';

// portfolio
export const CHANGE_PORTFOLIO_FILTER = 'CHANGE_PORTFOLIO_FILTER';
export const TOGGLE_PORTFOLIO_FILTER_ANIMATION = 'TOGGLE_PORTFOLIO_FILTER_ANIMATION';
export const TOGGLE_PORTFOLIO_THUMBNAIL_ANIMATION = 'TOGGLE_PORTFOLIO_THUMBNAIL_ANIMATION';

// skills
export const TOGGLE_SKILLS_PROGRESSBAR_ANIMATION = 'TOGGLE_SKILLS_PROGRESSBAR_ANIMATION';

// pubs
export const TOGGLE_PUBS_ENTRY_ANIMATION = 'TOGGLE_PUBS_ENTRY_ANIMATION';


export const PLAY_SCROLL_ANIMATION = 'PLAY_SCROLL_ANIMATION';
export const RESET_SCROLL_ANIMATION = 'RESET_SCROLL_ANIMATION';
