// home
export const LOAD_JSON_DATA = 'LOAD_JSON_DATA';

// about
export const TOGGLE_ABOUT_ICON_ANIMATION = 'TOGGLE_ABOUT_ICON_ANIMATION';

// portfolio
export const CHANGE_PORTFOLIO_FILTER = 'CHANGE_PORTFOLIO_FILTER';
export const TOGGLE_PORTFOLIO_FILTER_ANIMATION = 'TOGGLE_PORTFOLIO_FILTER_ANIMATION';
export const TOGGLE_PORTFOLIO_THUMBNAIL_ANIMATION = 'TOGGLE_PORTFOLIO_THUMBNAIL_ANIMATION';

// skills
export const TOGGLE_SKILLS_PROGRESSBAR_ANIMATION = 'TOGGLE_SKILLS_PROGRESSBAR_ANIMATION';

// stats
export const TOGGLE_STATS_COUNTER_ANIMATION = 'TOGGLE_STATS_COUNTER_ANIMATION';
export const TOGGLE_STATS_GITHUB_ANIMATION = 'TOGGLE_STATS_GITHUB_ANIMATION';

// pubs
export const TOGGLE_PUBS_ENTRY_ANIMATION = 'TOGGLE_PUBS_ENTRY_ANIMATION';

// contact
export const CHANGE_CONTACT_FIELD = 'CHANGE_CONTACT_FIELD';
export const SUBMIT_CONTACT_EMAIL_WAIT = 'SUBMIT_CONTACT_EMAIL_WAIT';
export const SUBMIT_CONTACT_EMAIL_SUCCESS = 'SUBMIT_CONTACT_EMAIL_SUCCESS';
export const SUBMIT_CONTACT_EMAIL_ERROR = 'SUBMIT_CONTACT_EMAIL_ERROR';
export const SUBMIT_CONTACT_EMAIL_RESET = 'SUBMIT_CONTACT_EMAIL_RESET';
export const TOGGLE_CONTACT_ICON_ANIMATION = 'TOGGLE_CONTACT_ICON_ANIMATION';
export const TOGGLE_CONTACT_ITEM_ANIMATION = 'TOGGLE_CONTACT_ITEM_ANIMATION';


export const PLAY_SCROLL_ANIMATION = 'PLAY_SCROLL_ANIMATION';
export const RESET_SCROLL_ANIMATION = 'RESET_SCROLL_ANIMATION';
